<?xml version="1.0"?>
<rdf:RDF xmlns="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#"
     xml:base="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89"/>
    


    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Object Properties
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->

    


    <!-- http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#has_location -->

    <owl:ObjectProperty rdf:about="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#has_location">
        <rdfs:domain rdf:resource="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Disorder"/>
        <rdfs:range rdf:resource="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Location"/>
    </owl:ObjectProperty>
    


    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Classes
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->

    


    <!-- http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Brain -->

    <owl:Class rdf:about="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Brain">
        <rdfs:subClassOf rdf:resource="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Location"/>
    </owl:Class>
    


    <!-- http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#CardiacDisorder -->

    <owl:Class rdf:about="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#CardiacDisorder">
        <rdfs:subClassOf rdf:resource="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Disorder"/>
    </owl:Class>
    


    <!-- http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#CriticalDisorder -->

    <owl:Class rdf:about="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#CriticalDisorder">
        <rdfs:subClassOf rdf:resource="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Disorder"/>
    </owl:Class>
    


    <!-- http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Disorder -->

    <owl:Class rdf:about="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Disorder"/>
    


    <!-- http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Heart -->

    <owl:Class rdf:about="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Heart">
        <rdfs:subClassOf rdf:resource="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Location"/>
    </owl:Class>
    


    <!-- http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Location -->

    <owl:Class rdf:about="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Location"/>
    


    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // General axioms
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->

    <owl:Class>
        <owl:intersectionOf rdf:parseType="Collection">
            <rdf:Description rdf:about="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Disorder"/>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#has_location"/>
                <owl:someValuesFrom rdf:resource="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#Brain"/>
            </owl:Restriction>
        </owl:intersectionOf>
        <rdfs:subClassOf rdf:resource="http://www.semanticweb.org/jiba/ontologies/2023/0/untitled-ontology-89#CriticalDisorder"/>
    </owl:Class>
</rdf:RDF>



<!-- Generated by the OWL API (version 4.5.9.2019-02-01T07:24:44Z) https://github.com/owlcs/owlapi -->

